-- BANK
INSERT INTO BANK VALUES(1, '농협');
INSERT INTO BANK VALUES(2, '국민');
INSERT INTO BANK VALUES(3, '우리');
INSERT INTO BANK VALUES(4, '하나');
-- PAY_CATEGORY
INSERT INTO PAY_CATEGORY VALUES(1, '충전');
INSERT INTO PAY_CATEGORY VALUES(2, '사용');
INSERT INTO PAY_CATEGORY VALUES(3, '출금');
-- BOOK_STATE
INSERT INTO BOOK_STATE	VALUES (1, '예약확인중');
INSERT INTO BOOK_STATE	VALUES (2, '수거예정');
INSERT INTO BOOK_STATE	VALUES (3, '수거중');
INSERT INTO BOOK_STATE	VALUES (4, '세탁진행중');
INSERT INTO BOOK_STATE	VALUES (5, '세탁완료');
INSERT INTO BOOK_STATE	VALUES (6, '배달예정');
INSERT INTO BOOK_STATE	VALUES (7, '배달중');
INSERT INTO BOOK_STATE	VALUES (8, '배달완료');
INSERT INTO BOOK_STATE	VALUES (9, '예약거절');
INSERT INTO BOOK_STATE	VALUES (10, '정산완료');
-- CLOTHES
INSERT INTO CLOTHES	VALUES (1, '상의/자켓');
INSERT INTO CLOTHES	VALUES (2, '하의');
INSERT INTO CLOTHES	VALUES (3, '스커트');
INSERT INTO CLOTHES	VALUES (4, '와이셔츠/남방');
INSERT INTO CLOTHES	VALUES (5, '티셔츠');
INSERT INTO CLOTHES	VALUES (6, '블라우스');      
INSERT INTO CLOTHES	VALUES (7, '원피스');    
INSERT INTO CLOTHES	VALUES (8, '스웨터/가디건');    
INSERT INTO CLOTHES	VALUES (9, '봄가을점퍼/아웃도어');    
INSERT INTO CLOTHES	VALUES (10, '코트');    
INSERT INTO CLOTHES	VALUES (11, '가죽/모피의류');    
INSERT INTO CLOTHES	VALUES (12, '겨울패딩/점퍼');    
INSERT INTO CLOTHES	VALUES (13, '넥타이');    
INSERT INTO CLOTHES	VALUES (14, '스카프/목도리');    
INSERT INTO CLOTHES	VALUES (15, '이불/침구류');    
INSERT INTO CLOTHES	VALUES (16, '커튼/카페트');   
INSERT INTO CLOTHES	VALUES (17, '한복류');   
INSERT INTO CLOTHES	VALUES (18, '모자');   
INSERT INTO CLOTHES	VALUES (19, '가방/기타가죽제품');   
INSERT INTO CLOTHES	VALUES (20, '운동화/스니커즈류');   
-- FABRIC
INSERT INTO FABRIC VALUES (1, '면', '물세탁');
INSERT INTO FABRIC VALUES (2, '니트', '물세탁');
INSERT INTO FABRIC VALUES (3, '레이온', '드라이클리닝');
INSERT INTO FABRIC VALUES (4, '데님', '물세탁');
INSERT INTO FABRIC VALUES (5, '실크/쉬폰', '손세탁');
INSERT INTO FABRIC VALUES (6, '린넨', '손세탁');
INSERT INTO FABRIC VALUES (7, '퍼', '드라이클리닝');
INSERT INTO FABRIC VALUES (8, '앙고라', '드라이클리닝');
INSERT INTO FABRIC VALUES (9, '가죽', '가죽 전용 드라이클리닝');
-- FAVORITE
INSERT INTO FAVORITE VALUES(FAVORITE_SEQ.NEXTVAL, 'a1234', 231);
INSERT INTO FAVORITE VALUES(FAVORITE_SEQ.NEXTVAL, 'b1234', 231);
INSERT INTO FAVORITE VALUES(FAVORITE_SEQ.NEXTVAL, 'c1234', 231);
-- PAY_ACCOUNT
INSERT INTO PAY_ACCOUNT VALUES(PAY_ACCOUNT_SEQ.NEXTVAL, 1, 1, '1002438409230', 'N');
INSERT INTO PAY_ACCOUNT VALUES(PAY_ACCOUNT_SEQ.NEXTVAL, 2, 2, '1002438409231', 'N');


-- BOOK (총가격 수정해야함)
INSERT INTO BOOK VALUES (BOOK_SEQ.NEXTVAL, 231, 'a1234', 1, 1,  systimestamp, '깨끗하게 부탁드려요', 1, 6000, systimestamp);
INSERT INTO BOOK VALUES (BOOK_SEQ.NEXTVAL, 231, 'a1234', 2, 2,  systimestamp, '소매에 와인 얼룩있어요.', 3, 12000, systimestamp);
INSERT INTO BOOK VALUES (BOOK_SEQ.NEXTVAL, 231, 'a1234', 9, 1,  systimestamp,  null, 2, 4000, systimestamp);
INSERT INTO BOOK VALUES (BOOK_SEQ.NEXTVAL, 231, 'a1234', 8, 1,  systimestamp, '깨끗하게 부탁드려요', 2, 3000, systimestamp);
INSERT INTO BOOK VALUES (BOOK_SEQ.NEXTVAL, 231, 'b1234', 1, 1,  systimestamp, '새옷처럼 만들어주세요. 꼭.', 2, 4000, systimestamp);
INSERT INTO BOOK VALUES (BOOK_SEQ.NEXTVAL, 231, 'b1234', 2, 2,  systimestamp, null, 3, 11000, systimestamp);
INSERT INTO BOOK VALUES (BOOK_SEQ.NEXTVAL, 231, 'b1234', 8, 1,  systimestamp, '깨끗하게 부탁드려요', 1, 3500, systimestamp);
INSERT INTO BOOK VALUES (BOOK_SEQ.NEXTVAL, 231, 'b1234', 10, 1,  systimestamp, '깨끗하게 세탁해주세요.', 2, 3000, systimestamp);
INSERT INTO BOOK VALUES (BOOK_SEQ.NEXTVAL, 231, 'c1234', 1, 1,  systimestamp, '깨끗하게 부탁드려요!!!', 2, 5000, systimestamp);
-- BOOK_LINE
INSERT INTO BOOK_LINE VALUES (BOOK_LINE_SEQ.NEXTVAL, 1, 1, 1, 6000);
INSERT INTO BOOK_LINE VALUES (BOOK_LINE_SEQ.NEXTVAL, 2, 2, 2, 7000);
INSERT INTO BOOK_LINE VALUES (BOOK_LINE_SEQ.NEXTVAL, 2, 3, 3, 5000);
INSERT INTO BOOK_LINE VALUES (BOOK_LINE_SEQ.NEXTVAL, 3, 4, 4, 4000);
INSERT INTO BOOK_LINE VALUES (BOOK_LINE_SEQ.NEXTVAL, 4, 5, 5, 3000);
INSERT INTO BOOK_LINE VALUES (BOOK_LINE_SEQ.NEXTVAL, 5, 2, 3, 4000);
INSERT INTO BOOK_LINE VALUES (BOOK_LINE_SEQ.NEXTVAL, 6, 3, 2, 8000);
INSERT INTO BOOK_LINE VALUES (BOOK_LINE_SEQ.NEXTVAL, 6, 4, 3, 3000);
INSERT INTO BOOK_LINE VALUES (BOOK_LINE_SEQ.NEXTVAL, 7, 5, 6, 3500);
INSERT INTO BOOK_LINE VALUES (BOOK_LINE_SEQ.NEXTVAL, 8, 4, 4, 3000);
INSERT INTO BOOK_LINE VALUES (BOOK_LINE_SEQ.NEXTVAL, 9, 3, 3, 5000);
-- ADJUST
INSERT INTO ADJUST VALUES(ADJUST_SEQ.NEXTVAL, 231, 8, systimestamp);
-- PAY_LOG
INSERT INTO PAY_LOG VALUES(PAY_LOG_SEQ.NEXTVAL, 1, 1, 1, 10000, systimestamp);
INSERT INTO PAY_LOG VALUES(PAY_LOG_SEQ.NEXTVAL, 2, 1, 1, 10000, systimestamp);
INSERT INTO PAY_LOG VALUES(PAY_LOG_SEQ.NEXTVAL, 1, 2, 1, 8000, systimestamp);
INSERT INTO PAY_LOG VALUES(PAY_LOG_SEQ.NEXTVAL, 2, 2, 1, 5000, systimestamp);
-- REVIEW
INSERT INTO REVIEW	VALUES (REVIEW_SEQ.NEXTVAL, 'a1234', 231, 4, '새옷처럼 아주 깨끗해요!!! ><', 5, systimestamp, systimestamp);
INSERT INTO REVIEW	VALUES (REVIEW_SEQ.NEXTVAL, 'b1234', 231, 7, '얼룩이 덜 지워졌어요 ㅡㅡ', 2, systimestamp, systimestamp);










