
  CREATE TABLE BANK 
   (	BANKID NUMBER(19,0) NOT NULL ENABLE, 
	BANKNAME VARCHAR2(255 CHAR) COLLATE USING_NLS_COMP, 
	 PRIMARY KEY (BANKID)
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE DATA  ENABLE
   )  DEFAULT COLLATION USING_NLS_COMP SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE DATA 


  CREATE TABLE BOOK 
   (	BOOKID NUMBER(19,0) NOT NULL ENABLE, 
	BOOKCOUNT NUMBER(10,0) NOT NULL ENABLE, 
	BOOKDATE TIMESTAMP (6), 
	BOOKMEMO VARCHAR2(255 CHAR) COLLATE USING_NLS_COMP, 
	BOOKMETHOD VARCHAR2(255 CHAR) COLLATE USING_NLS_COMP, 
	BOOKSTATE_ID NUMBER(19,0), 
	LAUNDRY_ID NUMBER(19,0), 
	USER_ID VARCHAR2(255 CHAR))




  CREATE TABLE BOOKLINE 
   (	BOOKLINEID NUMBER(19,0) NOT NULL ENABLE, 
	BOOKLINEFEE NUMBER(10,0) NOT NULL ENABLE, 
	CLOTHESFABRIC VARCHAR2(255 CHAR) COLLATE USING_NLS_COMP, 
	BOOK_ID NUMBER(19,0), 
	CLOTHES_ID NUMBER(10,0), 
	FABRIC_ID NUMBER(10,0), 
	 PRIMARY KEY (BOOKLINEID)
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE DATA  ENABLE, 
	 CONSTRAINT FKKJQ6XHDI8U8EWX756KOBU8RXD FOREIGN KEY (BOOK_ID)
	  REFERENCES BOOK (BOOKID) ENABLE, 
	 CONSTRAINT FKCLHN354VVA6A9U9PVGM67AHD0 FOREIGN KEY (CLOTHES_ID)
	  REFERENCES CLOTHES (CLOTHESID) ENABLE, 
	 CONSTRAINT FKOMSLU2TVFYGN29HT6ICO5K157 FOREIGN KEY (FABRIC_ID)
	  REFERENCES FABRIC (FABRICID) ENABLE
   )  DEFAULT COLLATION USING_NLS_COMP SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE DATA 




  CREATE TABLE BOOKSTATE 
   (	BOOKSTATEID NUMBER(10,0) NOT NULL ENABLE, 
	BOOKSTATENAME VARCHAR2(255 CHAR) COLLATE USING_NLS_COMP, 
	 PRIMARY KEY (BOOKSTATEID)
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE DATA  ENABLE
   )  DEFAULT COLLATION USING_NLS_COMP SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE DATA 





  CREATE TABLE CLOTHES 
   (	CLOTHESID NUMBER(10,0) NOT NULL ENABLE, 
	CLOTHESNAME VARCHAR2(255 CHAR) COLLATE USING_NLS_COMP, 
	 PRIMARY KEY (CLOTHESID)
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE DATA  ENABLE
   )  DEFAULT COLLATION USING_NLS_COMP SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE DATA 




  CREATE TABLE EXTRAFEE 
   (	EXTRAFEEID NUMBER(19,0) NOT NULL ENABLE, 
	FABRICFEE NUMBER(10,0) NOT NULL ENABLE, 
	FABRIC_ID NUMBER(10,0), 
	LAUNDRY_ID NUMBER(19,0), 
	 PRIMARY KEY (EXTRAFEEID)
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE DATA  ENABLE, 
	 CONSTRAINT FKKKXYVO41WMHBP22XV50GP68XF FOREIGN KEY (FABRIC_ID)
	  REFERENCES FABRIC (FABRICID) ENABLE, 
	 CONSTRAINT FK3UCR7OBG12YMDHB4B2MNHYSGM FOREIGN KEY (LAUNDRY_ID)
	  REFERENCES LAUNDRY (LAUNDRYID) ENABLE
   )  DEFAULT COLLATION USING_NLS_COMP SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE DATA 



  CREATE TABLE FEE 
   (	FEEID NUMBER(19,0) NOT NULL ENABLE, 
	CLOTHESFEE NUMBER(10,0) NOT NULL ENABLE, 
	CLOTHES_ID NUMBER(10,0), 
	LAUNDRY_ID NUMBER(19,0), 
	 PRIMARY KEY (FEEID)



  CREATE TABLE LAUNDRY 
   (	LAUNDRYID NUMBER(19,0) NOT NULL ENABLE, 
	LAUNDRYADDRESS VARCHAR2(255 CHAR) COLLATE USING_NLS_COMP, 
	LAUNDRYDELIVERYFEE NUMBER(10,0) NOT NULL ENABLE, 
	LAUNDRYNAME VARCHAR2(255 CHAR) COLLATE USING_NLS_COMP, 
	LAUNDRYTEL VARCHAR2(255 CHAR) COLLATE USING_NLS_COMP, 
	USER_ID VARCHAR2(255 CHAR) COLLATE USING_NLS_COMP, 
	 PRIMARY KEY (LAUNDRYID)
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE DATA  ENABLE
   )  DEFAULT COLLATION USING_NLS_COMP SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE DATA 



"
  CREATE TABLE "ADMIN"."METAPAY" 
   (	"METAPAYID" NUMBER(19,0) NOT NULL ENABLE, 
	"METAPAYBALANCE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"METAPAYPASSWORD" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"USER_ID" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("METAPAYID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE "DATA" "



"
  CREATE TABLE "ADMIN"."PAYACCOUNT" 
   (	"PAYACCOUNTID" NUMBER(19,0) NOT NULL ENABLE, 
	"PAYACCOUNTNUMBER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"PAYACCOUNTQUITSTATE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"BANK_ID" NUMBER(19,0), 
	"METAPAY_ID" NUMBER(19,0), 
	 PRIMARY KEY ("PAYACCOUNTID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE, 
	 CONSTRAINT "FKLU0BD7WN97V2MAXS5CQTJFRJF" FOREIGN KEY ("BANK_ID")
	  REFERENCES "ADMIN"."BANK" ("BANKID") ENABLE, 
	 CONSTRAINT "FKGLD105H2510I78GXFHDVHF4JC" FOREIGN KEY ("METAPAY_ID")
	  REFERENCES "ADMIN"."METAPAY" ("METAPAYID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE "DATA" "





"
  CREATE TABLE "ADMIN"."PAYCATEGORY" 
   (	"PAYCATEGORYID" NUMBER(19,0) NOT NULL ENABLE, 
	"PAYCATEGORYNAME" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("PAYCATEGORYID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE "DATA" "



"
  CREATE TABLE "ADMIN"."PAYLOG" 
   (	"PAYLOGID" NUMBER(19,0) NOT NULL ENABLE, 
	"PAYLOGAMOUNT" NUMBER(19,0), 
	"PAYLOGINSERTDATE" TIMESTAMP (6), 
	"METAPAY_ID" NUMBER(19,0), 
	"PAY_ACCOUNT_ID" NUMBER(19,0), 
	"PAY_CATEGORY_ID" NUMBER(19,0), 
	 PRIMARY KEY ("PAYLOGID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE, 
	 CONSTRAINT "FKS53I56YC293A1N16X8IBRXCA1" FOREIGN KEY ("METAPAY_ID")
	  REFERENCES "ADMIN"."METAPAY" ("METAPAYID") ENABLE, 
	 CONSTRAINT "FK6JG87QH4U26CUIFQJH1T12RE" FOREIGN KEY ("PAY_ACCOUNT_ID")
	  REFERENCES "ADMIN"."PAYACCOUNT" ("PAYACCOUNTID") ENABLE, 
	 CONSTRAINT "FKKBH11QP2L9IW46J2PS458RDIP" FOREIGN KEY ("PAY_CATEGORY_ID")
	  REFERENCES "ADMIN"."PAYCATEGORY" ("PAYCATEGORYID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE "DATA" "





"
  CREATE TABLE "ADMIN"."REVIEW" 
   (	"REVIEWID" NUMBER(19,0) NOT NULL ENABLE, 
	"BOOKID" NUMBER(19,0), 
	"REVIEWCONTENT" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"REVIEWINSERTDATE" TIMESTAMP (6), 
	"REVIEWRATE" NUMBER(19,0), 
	"REVIEWUPDATEDATE" TIMESTAMP (6), 
	"USER_ID" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("REVIEWID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE "DATA" "